"""projects table

Revision ID: dbf2b0cdf4d1
Revises: b3b060bbb15f
Create Date: 2018-12-11 21:00:48.411993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf2b0cdf4d1'
down_revision = 'b3b060bbb15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('frames_saved', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_frames_saved'), 'project', ['frames_saved'], unique=False)
    op.create_index(op.f('ix_project_last_update'), 'project', ['last_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_last_update'), table_name='project')
    op.drop_index(op.f('ix_project_frames_saved'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
